version: "3.9"

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${FRONT}_img
    container_name: ${FRONT}_ctn
    env_file:
      - .env
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    volumes:
      - .:/app
    restart: unless-stopped

  backend:
    build:
      context: ../MiniBNB
    container_name: minibnb-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5235:8080"

